/*
  ____  _       _            _             _       
 / ___|(_)_ __ | | __  _ __ | |_   _  __ _(_)_ __  
 \___ \| | '_ \| |/ / | '_ \| | | | |/ _` | | '_ \ 
  ___) | | | | |   <  | |_) | | |_| | (_| | | | | |
 |____/|_|_| |_|_|\_\ | .__/|_|\__,_|\__, |_|_| |_|
                      |_|            |___/         
# A Template for UnoQSinkPlugin, a Sink Plugin
# Generated by the command: plugin -t sink -d . UnoQSink
# Hostname: Fram-IV
# Current working directory: /Users/p4010/Develop/MADS_plugins/arduinoQ_plugin
# Creation date: 2026-06-10T11:41:16.730+0200
# NOTICE: MADS Version 2.1.1
*/

// Mandatory included headers
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

#include "rpc.hpp"

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "unoq_sink"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class UnoQSinkPlugin : public Sink<json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Sink::Sink; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    if (!_setup_ok) {
      cerr << "Plugin is not properly set up: " << _error << endl;
      return return_type::critical;
    }
    try {
      auto rpc_result = _rpc_client.call(input);
      if (_params["verbose"].get<bool>()) {
        cout << "RPC call " << input["function"] 
             << " succeeded: " << rpc_result.to_json() << endl;
      } 
    } catch (const std::exception &e) {
       _error = e.what();
       cerr << "RPC call failed: " << e.what() << endl;
       return return_type::error;
     }

    return return_type::success;
  }

  void set_params(const json &params) override { 
    Sink::set_params(params);
    _params["verbose"] = false;
    _params.merge_patch(params);
    
    try {
      _socket_path = _params["socket_path"].get<string_view>();
    } catch (const json::exception &e) {
      _socket_path = RPCClient::default_socket_path;
    } 

    if (_setup_ok) {
      try {
        _rpc_client.connect(_socket_path);
      } catch (const std::exception &e) {
        _error = "Failed to connect to RPC server: " + string(e.what());
        _setup_ok = false;
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"socket_path", string(_socket_path)},
      {"verbose", _params["verbose"].get<bool>() ? "true" : "false"}
    };
  };

private:
  json _rpc_call = json::object();
  bool _setup_ok = true;
  RPCClient::Client _rpc_client{};
  string_view _socket_path = RPCClient::default_socket_path;
};



/*
  ____  _             _             _      _                
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __ 
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |   
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|   
                |___/                                      
Enable the class as plugin 
*/
INSTALL_SINK_DRIVER(UnoQSinkPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  UnoQSinkPlugin plugin;
  json input, params;
  
  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.load_data(input);

  return 0;
}
