/*
  ____                                   _             _
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/
# A Template for UnoQSourcePlugin, a Source Plugin
# Generated by the command: plugin -t source -d UnoQ_source UnoQSourcePlugin
# Hostname: Fram-IV
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-06-09T13:28:17.357+0200
# NOTICE: MADS Version 2.1.1
*/
// Mandatory included headers
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <source.hpp>

#include "rpc.hpp"

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "unoq_source"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class UnoQSourcePlugin : public Source<json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Source::Source; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out,
                         vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_setup_ok) {
      out["error"] = _error;
      return return_type::critical;
    }
    if (!_agent_id.empty())
      out["agent_id"] = _agent_id;

    try {
      auto rpc_result = _rpc_client.call(_rpc_call);
      out["result"] = rpc_result.to_json();
    } catch (const std::exception &e) {
      out["error"] = e.what();
      cout << "RPC call failed: " << e.what() << endl;
      return return_type::error;
    }

    return return_type::success;
  }

  void set_params(const json &params) override {
    Source::set_params(params);
    _params.merge_patch(params);

    try {
      _socket_path = _params["socket_path"].get<string_view>();
    } catch (const json::exception &e) {
      _socket_path = RPCClient::default_socket_path;
    } 

    try {
      _rpc_call["function"] = _params["rpc_call"];
    } catch (const json::exception &e) {
      _error = "Invalid rpc_call parameter: " + string(e.what());
      _setup_ok = false;
    }

    try {
      _rpc_call["parameters"] = _params["rpc_args"];
    } catch (const json::exception &e) {
      _error = "Invalid rpc_args parameter: " + string(e.what());
      _setup_ok = false;
    }

    if (_setup_ok) {
      try {
        _rpc_client.connect(_socket_path);
      } catch (const std::exception &e) {
        _error = "Failed to connect to RPC server: " + string(e.what());
        _setup_ok = false;
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    return {
        {"socket_path", string(_socket_path)},
        {"rpc_call", _rpc_call.dump()}
    };
  };

private:
  json _rpc_call = json::object();
  bool _setup_ok = true;
  RPCClient::Client _rpc_client{};
  string_view _socket_path = RPCClient::default_socket_path;
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(UnoQSourcePlugin, json)

/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/

int main(int argc, char const *argv[]) {
  UnoQSourcePlugin plugin;
  json output, params;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.get_output(output);

  // Produce output
  cout << "Output: " << output << endl;

  // Desired LED value
  bool led_state = true;

  RPCClient::Client client(RPCClient::default_socket_path);
  client.call("set_led", {led_state});

  return 0;
}
