/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for UnoqfilterPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d . UnoQFilter
# Hostname: Fram-IV
# Current working directory: /Users/p4010/Develop/MADS_plugins/arduinoQ_plugin
# Creation date: 2026-06-10T11:42:55.051+0200
# NOTICE: MADS Version 2.1.1
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

#include "rpc.hpp"

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "unoq_filter"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class UnoQFilterPlugin : public Filter<json, json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Filter::Filter; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    if (!_setup_ok) {
      cerr << "Plugin is not properly set up: " << _error << endl;
      return return_type::critical;
    }
    if (!input.contains("rpc_func") || !input["rpc_func"].is_string()) {
      _error = "Input JSON must contain a string field 'rpc_func'";
      if (_params["verbose"].get<bool>()) {
        cerr << "Error: " << _error << endl;
      }
      return return_type::error;
    }

    if (!input.contains("rpc_args") || !input["rpc_args"].is_array()) {
      _error = "Input JSON must contain an array field 'rpc_args'";
      if (_params["verbose"].get<bool>()) {
        cerr << "Error: " << _error << endl;
      }
      return return_type::error;
    }
    _rpc_call = input;
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;

    try {
      auto rpc_result = _rpc_client.call(_rpc_call);
      out["result"] = rpc_result.to_json();
    } catch (const std::exception &e) {
      out["error"] = e.what();
      cout << "RPC call failed: " << e.what() << endl;
      return return_type::error;
    }

    return return_type::success;
  }
  
  void set_params(const json &params) override {
    Filter::set_params(params);
    _params["verbose"] = false;
    _params.merge_patch(params);
    
    try {
      _socket_path = _params["socket_path"].get<string_view>();
    } catch (const json::exception &e) {
      _socket_path = RPCClient::default_socket_path;
    } 

    if (_setup_ok) {
      try {
        _rpc_client.connect(_socket_path);
      } catch (const std::exception &e) {
        _error = "Failed to connect to RPC server: " + string(e.what());
        _setup_ok = false;
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"socket_path", string(_socket_path)},
      {"verbose", _params["verbose"].get<bool>() ? "true" : "false"}
    };
  };

private:
  json _rpc_call = json::object();
  bool _setup_ok = true;
  RPCClient::Client _rpc_client{};
  string_view _socket_path = RPCClient::default_socket_path;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(UnoQFilterPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  UnoQFilterPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["socket_path"] = "/tmp/mads-rpc.sock";
  params["verbose"] = true;

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["rpc_func"] = "echo";
  input["rpc_args"] = {
    42,
    "hello",
    true
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

